### ISSUE TITLE
libssh2 patching

### ISSUE THREAD

**Issue by haam3r** [cert-ee/s4a#1]
Due to changes at github.com the latest libssh2 version in Ubuntu 16.04 is unable to communicate with github private repos.

Workaround currently:
```
wget https://github.com/libssh2/libssh2/archive/master.zip
sudo apt-get install unzip cmake
unzip master.zip
cd libssh2-master/
mkdir bin
cd bin/ && cd bin 
cmake ..
cmake -DBUILD_SHARED_LIBS=ON --build .
cmake --build .
sudo mv /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1 /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1.bak && cp src/libssh2.so.1.0.1 /usr/lib/x86_64-linux-gnu
```

Probably most elegant workaround would be to build our own deb of a more recent version of libsssh2.

**Comment by voldemarpanso** [comment]
Created a build script for libssh2. Try it out.

**Comment by haam3r** [comment]
Have debs  in live repo up, tested and working. Closing with #61c2b45a61922e291da518afd439e9ac0204314b
#e5e2ffdd6d320e2939f74aab970f2cabaeaddd20
