### ISSUE TITLE
feedback from installer script not received to central

### ISSUE THREAD

**Issue by haam3r** [cert-ee/s4a#10]
Summary for local
		-------------
		Succeeded: 25 (changed=23)
		Failed:     5
		-------------
		Total states run:     30
		Total run time:  118.590 s
		---
Send to CERT-EE?  y
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7

	Log sent to CERT-EE:
		ID: 2153940822b853511d9e5c7d5a8405c4
		Received case nr:

**Comment by haam3r** [comment]
please test
cert-ee/s4a-central@bc8f422

**Comment by voldemarpanso** [comment]
Updated messaging a bit to get more useful feedback
from those errors, 1e29c43

**Comment by voldemarpanso** [comment]
Updated installer a bit. We tested this and only notable issue
was, that if API is running on port 5000 you have to be sure if it's
running on http or https (as it's not obvious) and not to forget to
configure URL in installer script accordingly.

**Comment by voldemarpanso** [comment]
We haven't ran into any issues now for a while. Are you?
