### ISSUE TITLE
Script built central dpkg not working

### ISSUE THREAD

**Issue by TNogisto** [cert-ee/s4a#12]
After building the s4a-central with the "build_central.sh" script, trying to install the resulting package gives the following error:

s4a-central : Depends: mongodb-org but it is not installable
               Depends: yarn but it is not installable
               Depends: pwgen but it is not going to be installed

OS is Ubuntu 16.04.

**Comment by haam3r** [comment]
Package was not installed using the Salt states. Therefore dependency's were missing.

**Comment by voldemarpanso** [comment]
I'm not following the issue here. The requirements (dependencies) are clearly
stated, if you install it manually you also have to provide deps manually.

**Comment by haam3r** [comment]
@voldemarpanso Yep, @TNogisto did not realize that. Closing the issue as solved.
