### ISSUE TITLE
Locale issues with salt bootstrap script

### ISSUE THREAD

**Issue by haam3r** [cert-ee/s4a#2]
With non english locale, salt bootstrap script seems to fail at times.
Fix would be to add
```bash
export LC_ALL=C
```
to installer script

**Comment by haam3r** [comment]
Should be fixed with: https://github.com/cert-ee/s4a/commit/e227828561f23794199ac9f0fa755897242a5b23

**Comment by voldemarpanso** [comment]
Salt worked, but translation was not used. I tuned this a bit,
should work fine now with any locale.
