### ISSUE TITLE
moloch user creation bug

### ISSUE THREAD

**Issue by roheline** [cert-ee/s4a#22]
Existing s4a users are not added to moloch user database during moloch initial install.

If moloch is installed later from the components menu the existing users are not added to moloch database.
Default s4a admin user is also not added.

**Comment by voldemarpanso** [comment]
Just a note here that this is not installer issue as it's not aware of users. 
User management is done via "detector" itself, functionality needs review.

**Comment by voldemarpanso** [comment]
And additionally: I can't confirm admin user issue

**Comment by voldemarpanso** [comment]
Check PR:
https://github.com/cert-ee/s4a/pull/34
Simple fix for the issue.
