### ISSUE TITLE
Evebox agent socket too many open files

### ISSUE THREAD

**Issue by haam3r** [cert-ee/s4a#4]
In some instances seeing these kinds of errors:
```bash
Mar 22 10:30:52 aptll560 evebox[3407]: 2018-03-22 10:30:52 (evefileprocessor.go:207) <Error> -- Failed to commit events, will try again: : Post http://localhost:5636/api/1/submit: dial tcp 127.0.0.1:5636: socket: too many open files
```
These are preventing Suricata alerts from reacing elasticsearch.

Just raise ulimits for evebox or should we try something else?

**Comment by voldemarpanso** [comment]
Updated evebox state to provide modifed service file for evebox, to increase opened files limits.

**Comment by haam3r** [comment]
https://github.com/cert-ee/s4a/commit/ed8a1e4bf79788cca029d5a79db5c2017124af06
