### ISSUE TITLE
Components view does not show ongoing tasks

### ISSUE THREAD

**Issue by roheline** [cert-ee/s4a#5]
When a selecting components view and some view related task (install,uninstal,enable,restart) is already running it is not shown as a running task.

**Comment by tavipoldma** [comment]
loading is now persintent
https://github.com/cert-ee/s4a-detector/pull/4/commits/35ade8a44971cdb1eb0da400338a0f07ca0895a2

needs a bit more work

**Comment by tavipoldma** [comment]
closing
